name: fraze_pocket
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.4+1

environment:
  sdk: ^3.4.3

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.69.2
  change_app_package_name: ^1.4.0
  google_fonts: ^6.2.1
  easy_date_timeline: ^1.0.4
  gaimon: ^1.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  intl: ^0.19.0
  pull_down_button: ^0.10.2
  flutter_svg: ^2.0.14
  provider: ^6.0.0
  flagsmith: ^6.0.0
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.14.1
  get_ip_address: ^0.0.7
  http: ^1.2.2
  get_it: ^8.0.2
  custom_progressbar: ^0.0.2
  shared_preferences: ^2.3.3
  in_app_review: ^2.0.9
  is_first_run: ^1.0.0
  url_launcher: ^6.3.1
  flutter_email_sender: ^6.0.3
  flutter_app_info: ^3.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_native_splash:
  image: assets/images/icon.png
  color: '#0D1A22'

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"


flutter:
  uses-material-design: true
  assets: 
    - assets/images/
  fonts:
    - family: Onest
      fonts:
        - asset: assets/fonts/Onest-Black.ttf
          weight: 900
        - asset: assets/fonts/Onest-Bold.ttf
          weight: 700
        - asset: assets/fonts/Onest-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Onest-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Onest-Light.ttf
          weight: 300
        - asset: assets/fonts/Onest-Medium.ttf
          weight: 500
        - asset: assets/fonts/Onest-Regular.ttf
          weight: 400
        - asset: assets/fonts/Onest-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Onest-Thin.ttf
          weight: 100